### ISSUE TITLE
gcc warnings

### ISSUE THREAD

**Issue by simbulu** [supremeedible/json2csv#1]
Thanks for at pretty little program that saved my day.

Would it be possible to resolve the warnings generated by gcc using -Wall ?

...torkil...

$ gcc -Wall -pedantic -std=gnu99 json2csv.c -o json2csv 
json2csv.c: In function ‘copyValue’:
json2csv.c:258:23: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
                 c = p & 0x3f | 0x80;
                       ^
json2csv.c:288:54: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
                 buffer[(*bufi)++] = (char)((p >> 12) & 0x3f | 0x80);
                                                      ^
json2csv.c:289:53: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
                 buffer[(*bufi)++] = (char)((p >> 6) & 0x3f | 0x80);
                                                     ^
json2csv.c:291:23: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
                 c = p & 0x3f | 0x80;
                       ^
json2csv.c:301:53: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
                 buffer[(*bufi)++] = (char)((p >> 6) & 0x3f | 0x80);
                                                     ^
json2csv.c:303:23: warning: suggest parentheses around arithmetic in operand of ‘|’ [-Wparentheses]
                 c = p & 0x3f | 0x80;
                       ^
json2csv.c:317:58: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
       if (!noempty || *bufi > i + 1 || quote != Q_STRING && *bufi > i)
                                                          ^
json2csv.c:338:59: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
     else if (c == 't' || c == 'f' || c == 'n' || c >= '0' && c <= '9' || c == '.')
                                                           ^
json2csv.c:340:18: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
       if (nonull && c == 'n' || nofalse && c == 'f')
                  ^
json2csv.c: In function ‘copyObject’:
json2csv.c:399:7: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
       while (r = copyProperty(file, fields, indices, fieldn, fieldi, bufi, depth))
       ^
json2csv.c:424:7: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
       while (r = copyObject(file, fields, indices, fieldn, fieldi, bufi, depth))
       ^
json2csv.c:422:11: warning: unused variable ‘i’ [-Wunused-variable]
       int i;
           ^
json2csv.c:445:59: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
     else if (c == 't' || c == 'f' || c == 'n' || c >= '0' && c <= '9' || c == '.')
                                                           ^
json2csv.c: In function ‘processObject’:
json2csv.c:626:7: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
       while (r = copyProperty(file, fields, indices, n, 0, &bufi, -2))
       ^
json2csv.c:653:7: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
       while (r = copyObject(file, fields, indices, n, 0, &bufi, -2))
       ^
json2csv.c:685:59: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
     else if (c == 't' || c == 'f' || c == 'n' || c >= '0' && c <= '9' || c == '.')
                                                           ^
json2csv.c: In function ‘readObject’:
json2csv.c:854:7: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
       while (r = readProperty(file, key, fields))
       ^
json2csv.c:875:7: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
       while (r = readObject(file, key, fields, 0))
       ^
json2csv.c:922:59: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
     else if (c == 't' || c == 'f' || c == 'n' || c >= '0' && c <= '9' || c == '.')

**Comment by supremeedible** [comment]
The clanging sound has been silenced! Welcome to github.
